/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface Expense {
  'id' : string,
  'date' : bigint,
  'description' : string,
  'category' : string,
  'amount' : bigint,
}
export type InvoiceStatus = { 'paid' : null } |
  { 'sent' : null } |
  { 'overdue' : null } |
  { 'draft' : null };
export interface LineItem {
  'name' : string,
  'description' : string,
  'productId' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface Product {
  'id' : string,
  'stockQuantity' : bigint,
  'name' : string,
  'description' : string,
  'category' : string,
  'price' : bigint,
}
export interface _SERVICE {
  'addExpense' : ActorMethod<[string, string, bigint, string, bigint], string>,
  'addProduct' : ActorMethod<
    [string, string, string, bigint, bigint, string],
    string
  >,
  'createCustomer' : ActorMethod<
    [string, string, string, string, string, bigint],
    string
  >,
  'createInvoice' : ActorMethod<
    [string, string, Array<LineItem>, bigint, InvoiceStatus, bigint, bigint],
    string
  >,
  'deleteCustomer' : ActorMethod<[string], string>,
  'deleteExpense' : ActorMethod<[string], string>,
  'deleteProduct' : ActorMethod<[string], string>,
  'getCustomerById' : ActorMethod<[string], [] | [Customer]>,
  'getExpenseById' : ActorMethod<[string], [] | [Expense]>,
  'getProductById' : ActorMethod<[string], [] | [Product]>,
  'updateCustomer' : ActorMethod<
    [string, string, string, string, string],
    string
  >,
  'updateExpense' : ActorMethod<
    [string, string, bigint, string, bigint],
    string
  >,
  'updateInvoiceStatus' : ActorMethod<[string, InvoiceStatus], string>,
  'updateProduct' : ActorMethod<
    [string, string, string, bigint, bigint, string],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];