/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LineItem = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const InvoiceStatus = IDL.Variant({
  'paid' : IDL.Null,
  'sent' : IDL.Null,
  'overdue' : IDL.Null,
  'draft' : IDL.Null,
});
export const Customer = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Expense = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'stockQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addExpense' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Int],
      [IDL.Text],
      [],
    ),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [IDL.Text],
      [],
    ),
  'createInvoice' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(LineItem),
        IDL.Nat,
        InvoiceStatus,
        IDL.Int,
        IDL.Int,
      ],
      [IDL.Text],
      [],
    ),
  'deleteCustomer' : IDL.Func([IDL.Text], [IDL.Text], []),
  'deleteExpense' : IDL.Func([IDL.Text], [IDL.Text], []),
  'deleteProduct' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getCustomerById' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], []),
  'getExpenseById' : IDL.Func([IDL.Text], [IDL.Opt(Expense)], []),
  'getProductById' : IDL.Func([IDL.Text], [IDL.Opt(Product)], []),
  'updateCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'updateExpense' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Int],
      [IDL.Text],
      [],
    ),
  'updateInvoiceStatus' : IDL.Func([IDL.Text, InvoiceStatus], [IDL.Text], []),
  'updateProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LineItem = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'productId' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const InvoiceStatus = IDL.Variant({
    'paid' : IDL.Null,
    'sent' : IDL.Null,
    'overdue' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Customer = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Expense = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'stockQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addExpense' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Int],
        [IDL.Text],
        [],
      ),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [IDL.Text],
        [],
      ),
    'createInvoice' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(LineItem),
          IDL.Nat,
          InvoiceStatus,
          IDL.Int,
          IDL.Int,
        ],
        [IDL.Text],
        [],
      ),
    'deleteCustomer' : IDL.Func([IDL.Text], [IDL.Text], []),
    'deleteExpense' : IDL.Func([IDL.Text], [IDL.Text], []),
    'deleteProduct' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getCustomerById' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], []),
    'getExpenseById' : IDL.Func([IDL.Text], [IDL.Opt(Expense)], []),
    'getProductById' : IDL.Func([IDL.Text], [IDL.Opt(Product)], []),
    'updateCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'updateExpense' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Int],
        [IDL.Text],
        [],
      ),
    'updateInvoiceStatus' : IDL.Func([IDL.Text, InvoiceStatus], [IDL.Text], []),
    'updateProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };